### ISSUE TITLE
what type of server

### ISSUE THREAD

**Issue by TerikKek** [3arthqu4ke/PingBypass#2]
like a dedicated ovh or a virtual machine and where would someone get it

**Comment by 3arthqu4ke** [comment]
A VM. I used Google Cloud Platform for it, they have a 90 day free trial and you can host all over the world. A friend of mine used contabo, a german server host which worked just as well if not better. So any VPS works.

**Comment by TerikKek** [comment]
for google cloud what exactly did u use

**Comment by 3arthqu4ke** [comment]
Google Cloud Platform -> VM Instances -> Create Instance -> I created one with "2vCPU, 8GB" on Debian Linux.
Dont forget to create a Firewall Rule to open the port you want. Then I installed java etc.. And used Remote Desktop for Minecraft later on because that makes the process easier. Also PuTTy and WinSCP for files. 
https://cloud.google.com/free <- Here you find the free trial and if you google you''ll find articles and tutorials on GCP everywhere.

**Comment by phonkplugg** [comment]
> Google Cloud Platform -> VM Instances -> Create Instance -> I created one with "2vCPU, 8GB" on Debian Linux.
> Dont forget to create a Firewall Rule to open the port you want. Then I installed java etc.. And used Remote Desktop for Minecraft later on because that makes the process easier. Also PuTTy and WinSCP for files.
> https://cloud.google.com/free <- Here you find the free trial and if you google you''ll find articles and tutorials on GCP everywhere.

minecraft 1.12 is not working for me, only 1.13-1.16. im using openjdk 8, ubuntu machine (Google Cloud), 15gm ram, 4 vGPU cores. As desktop, im using cinnamon

**Comment by B0I-Mark-II** [comment]
> 
> 
> Google Cloud Platform -> VM Instances -> Create Instance -> I created one with "2vCPU, 8GB" on Debian Linux.
> Dont forget to create a Firewall Rule to open the port you want. Then I installed java etc.. And used Remote Desktop for Minecraft later on because that makes the process easier. Also PuTTy and WinSCP for files.
> https://cloud.google.com/free <- Here you find the free trial and if you google you''ll find articles and tutorials on GCP everywhere.

what method do you use to rdp to the server? xrdp doesn't seem to work
