### ISSUE TITLE
how do i find the internal ip and port if i connect to the vps through a tcp connection

### ISSUE THREAD

**Issue by jamesbond78** [3arthqu4ke/PingBypass#30]
for example what should i write in the ip and port if i connect to the vps using this "8.tcp.ngrok.io:19860"

**Comment by 3arthqu4ke** [comment]
I would recommend building from the latest commit, since that one makes the server.json configure properly. If I understand you correctly you'd want to paste:

{
  "Bind": "NONE",
  "IServerIP": "8.tcp.ngrok.io",
  "Port": 19860,
  "NoRender": false,
  "Hidden": false,
  "Enabled": false,
  "Name": "PingBypass"
}

into your Server.json

**Comment by jamesbond78** [comment]
yeah it didnt work when i tried it. I guess ping bypass doesnt work on tlauncher
